id: IDC82C05A
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T08:36:18.295787'
last_modified: '2022-06-19T08:36:18.295799'
parser: null
source_metadata:
  title: Hagiography of the 54th Ngor abbot Byams pa kun dga bstan pai rgyal mtshan
    (1829–1870); Lamdre Lobshe, vol. ja, title no. 4
  author: འཇམ་དབྱངས་བློ་གཏེར་དབང་པོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-05);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/581
  bases:
    242d:
      title: Hagiography of the 54th Ngor abbot Byams pa kun dga bstan pai rgyal mtshan
        (1829–1870); Lamdre Lobshe, vol. ja, title no. 4
      order: 1
      base_file: 242d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
